# Generated by Django 2.1.7 on 2019-02-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputoutput',
            name='value',
        ),
    ]
