# Generated by Django 2.1.7 on 2019-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_pipeline_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='data',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='json_value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
