# Generated by Django 2.1.7 on 2019-02-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_inputoutput_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='block',
            name='outputs',
        ),
    ]
