# Generated by Django 2.1.7 on 2019-02-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20190218_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='inputs',
            field=models.ManyToManyField(related_name='inputs', to='front.InputOutput'),
        ),
        migrations.AddField(
            model_name='block',
            name='outputs',
            field=models.ManyToManyField(related_name='outputs', to='front.InputOutput'),
        ),
    ]
