# Generated by Django 2.1.7 on 2019-02-18 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20190218_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputoutput',
            name='value',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.InputOutputType'),
        ),
    ]
