# Generated by Django 2.1.7 on 2019-05-10 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0007_block_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.TextField()),
                ('logss', models.TextField()),
                ('pipeline', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Pipeline')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
