# Generated by Django 2.1.7 on 2019-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_auto_20190510_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresult',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
