# Generated by Django 2.1.7 on 2019-05-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_pipelineresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
