# Generated by Django 2.1.7 on 2019-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_pipeline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresult',
            name='worker_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
