# Generated by Django 2.1.7 on 2019-05-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_auto_20190511_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresult',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pipelineresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
