# Generated by Django 2.1.7 on 2019-05-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_auto_20190511_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelineresult',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
