# Generated by Django 2.1.7 on 2019-05-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_auto_20190511_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='vote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Vote'),
        ),
    ]
