# Generated by Django 2.1.7 on 2019-05-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_auto_20190517_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineResultImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.BinaryField(blank=True)),
                ('pipeline_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.PipelineResult')),
            ],
        ),
    ]
