# Generated by Django 2.1.7 on 2019-05-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0021_pipelineresultimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineresultimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
