# Generated by Django 2.1.7 on 2019-05-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_auto_20190521_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineresultimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
