# Generated by Django 2.1.7 on 2019-05-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20190521_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.UserProfile'),
        ),
    ]
