# Generated by Django 2.1.7 on 2019-05-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20190521_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scope',
            field=models.CharField(choices=[('p', 'Public'), ('f', 'Friends'), ('u', 'User')], default='p', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='scope',
            field=models.CharField(choices=[('p', 'Public'), ('f', 'Friends'), ('u', 'User')], default='f', max_length=1, null=True),
        ),
    ]
