# Generated by Django 2.1.7 on 2019-05-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20190521_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(null=True, to='social.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
