# Generated by Django 2.1.7 on 2019-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20190521_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(blank=True, choices=[('m', 'Man'), ('f', 'Women'), ('o', 'Other')], max_length=1, null=True),
        ),
    ]
