# Generated by Django 2.1.7 on 2019-05-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20190521_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='associated_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.PipelineResult'),
        ),
    ]
