# Generated by Django 2.1.7 on 2019-05-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20190521_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='friends',
            new_name='followings',
        ),
    ]
